services:
  kubo:
    image: ipfs/kubo:v0.43.0
    restart: unless-stopped
    volumes:
      - kubo_data:/data/ipfs
      - kubo_export:/export
    environment:
      IPFS_PROFILE: server
    ports:
      - "4001:4001"     # P2P
      - "127.0.0.1:5001:5001"     # API
      # - "8080:8080"     # Gateway
    command: ["daemon"]
    healthcheck:
      test: ["CMD", "ipfs", "id"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    stop_grace_period: 30s
    security_opt:
      - no-new-privileges:true
    labels:
      - pangolin.public-resources.$COMPOSE_PROJECT_NAME.name=$COMPOSE_PROJECT_NAME
      - pangolin.public-resources.$COMPOSE_PROJECT_NAME.full-domain=$HOST
      - pangolin.public-resources.$COMPOSE_PROJECT_NAME.protocol=http
      - pangolin.public-resources.$COMPOSE_PROJECT_NAME.ssl=true
      - pangolin.public-resources.$COMPOSE_PROJECT_NAME.auth.sso-enabled=true
      - pangolin.public-resources.$COMPOSE_PROJECT_NAME.auth.sso-roles[0]=Member
      - pangolin.public-resources.$COMPOSE_PROJECT_NAME.targets[0].method=http
      - pangolin.public-resources.$COMPOSE_PROJECT_NAME.targets[0].port=5001
      - pangolin.public-resources.$COMPOSE_PROJECT_NAME.targets[0].healthcheck.enabled=true
      - pangolin.public-resources.$COMPOSE_PROJECT_NAME.targets[0].healthcheck.hostname=$COMPOSE_PROJECT_NAME-kubo-1
      - pangolin.public-resources.$COMPOSE_PROJECT_NAME.targets[0].healthcheck.port=8080
      - pangolin.public-resources.$COMPOSE_PROJECT_NAME.targets[0].healthcheck.path=/ipfs/QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn
      - pangolin.public-resources.$COMPOSE_PROJECT_NAME.targets[0].healthcheck.method=GET
      - pangolin.public-resources.$COMPOSE_PROJECT_NAME.targets[0].healthcheck.status=200

      # Page de maintenance en mode automatique
      - pangolin.public-resources.$COMPOSE_PROJECT_NAME.maintenance.enabled=true
      - pangolin.public-resources.$COMPOSE_PROJECT_NAME.maintenance.type=automatic
      - pangolin.public-resources.$COMPOSE_PROJECT_NAME.maintenance.title=Maintenance en cours
      - pangolin.public-resources.$COMPOSE_PROJECT_NAME.maintenance.message=Le service est temporairement indisponible.

volumes:
  kubo_data:
  kubo_export:
      
networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
    
