app = "revika"
primary_region = "ams"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 9_096
min_machines_running = 0

[deploy]
  release_command = "/usr/local/bin/revika-node -data=/data -listen=/ip4/0.0.0.0/tcp/$REVIKA_PORT -public-ip=$PUBLIC_IP -advertise=true -capacity=$CAPACITY -log-format=json -log-level=$LOGLEVEL -metrics=:9096 -quota=$STORAGE_QUOTA -geoip=ip-api -bootstrap $SEED_ADDR"

[env]
  REPAIR_INTERVAL="1h"
  POW_DIFFICULTY=12
  PUBLIC_IP="0.0.0.0"
  CAPACITY=0
  LOGLEVEL="info"
  STORAGE_QUOTA=0
  REBALANCE_INTERVAL="1h"
  REVIKA_PORT=4001

[[mounts]]
destination = "/data"
source = "data"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
memory_mb = 256
